-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies KG271 TF5EE0048511",
  mode = "1920x1080@60.00",
  position = "1020x-1180",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Display 0x0706",
  mode = "1920x1080@60.02",
  position = "1020x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Display 0x0706", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Display 0x0706" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Display 0x0706" })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Display 0x0706" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Acer Technologies KG271 TF5EE0048511", default = true, persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Acer Technologies KG271 TF5EE0048511" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Acer Technologies KG271 TF5EE0048511" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Acer Technologies KG271 TF5EE0048511" })
