-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Display 0x0706",
  mode = "1920x1080@60.02",
  position = "1070x-338",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Microstep MSI G2412F BB9T054202601",
  mode = "1920x1080@60.00",
  position = "1070x-1514",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Display 0x0706", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Display 0x0706" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Display 0x0706" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Microstep MSI G2412F BB9T054202601", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Microstep MSI G2412F BB9T054202601" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Microstep MSI G2412F BB9T054202601" })
